//
//  AstraIcon.swift
//  AstraNotes
//
//  Generated from Google Material Symbols (Outlined variable font).
//  Codepoint source: Resources/Fonts/MaterialSymbolsOutlined.codepoints
//  Regenerate: node scripts/generate_icons.js
//

import SwiftUI

/// Google Material Symbols icons used across AstraNotes.
/// Raw value is the font PUA codepoint; render via AstraIconView.
enum AstraIcon: String, CaseIterable, Identifiable {
    var id: String { rawValue }

    /// SF Symbols: "square.grid.2x2"
    case gridView = ""
    /// SF Symbols: "mic.circle"
    case mic = ""
    /// SF Symbols: "text.document"
    case description = ""
    /// SF Symbols: "square.stack"
    case style = ""
    /// SF Symbols: "questionmark.circle"
    case help = ""
    /// SF Symbols: "book"
    case menuBook = ""
    /// SF Symbols: "brain"
    case psychology = ""
    /// SF Symbols: "graduationcap"
    case school = ""
    /// SF Symbols: "chart.bar"
    case barChart = ""
    /// SF Symbols: "heart.circle"
    case favorite = ""
    /// SF Symbols: "gearshape"
    case settings = ""
    /// SF Symbols: "pause"
    case pause = ""
    /// SF Symbols: "play"
    case playArrow = ""
    /// SF Symbols: "stop.fill"
    case stop = ""
    /// SF Symbols: "waveform"
    case graphicEq = ""
    /// SF Symbols: "arrow.down.doc"
    case download = ""
    /// SF Symbols: "folder"
    case folder = ""
    /// SF Symbols: "timer"
    case timer = ""
    /// SF Symbols: "forward"
    case arrowForward = ""
    /// SF Symbols: "arrow.left"
    case arrowBack = ""
    /// SF Symbols: "arrow.triangle.2.circlepath"
    case refresh = ""
    /// SF Symbols: "checkmark"
    case check = ""
    /// SF Symbols: "checkmark.circle"
    case checkCircle = ""
    /// SF Symbols: "checkmark.seal"
    case verified = ""
    /// SF Symbols: "xmark.circle.fill"
    case cancel = ""
    /// SF Symbols: "exclamationmark.triangle.fill"
    case warning = ""
    /// SF Symbols: "plus"
    case add = ""
    /// SF Symbols: "plus.circle"
    case addCircle = ""
    /// SF Symbols: "magnifyingglass"
    case search = ""
    /// SF Symbols: "sparkles"
    case autoAwesome = ""
    /// SF Symbols: "trash"
    case delete = ""
    /// SF Symbols: "paperplane"
    case send = ""
    /// SF Symbols: "square.and.arrow.up"
    case share = ""
    /// SF Symbols: "doc.on.doc"
    case contentCopy = ""
    /// SF Symbols: "doc.richtext"
    case article = ""
    /// SF Symbols: "star"
    case star = ""
    /// SF Symbols: "clock"
    case schedule = ""
    /// SF Symbols: "clock.arrow.2.circlepath"
    case history = ""
    /// SF Symbols: "calendar"
    case calendarMonth = ""
    /// SF Symbols: "link.circle"
    case link = ""
    /// SF Symbols: "info.circle"
    case info = ""
    /// SF Symbols: "pencil"
    case edit = ""
    /// SF Symbols: "pencil.and.outline"
    case editNote = ""
    /// SF Symbols: "chevron.down"
    case expandMore = ""
    /// SF Symbols: "chevron.right"
    case chevronRight = ""
    /// SF Symbols: "checklist"
    case checklist = ""
    /// SF Symbols: "list.bullet.rectangle"
    case notes = ""
    /// SF Symbols: "list.bullet.indent"
    case list = ""
    /// SF Symbols: "lightbulb"
    case lightbulb = ""
    /// SF Symbols: "eye"
    case visibility = ""
    /// SF Symbols: "person"
    case person = ""
    /// SF Symbols: "person.2"
    case group = ""
    /// SF Symbols: "gauge"
    case speed = ""
    /// SF Symbols: "function"
    case functions = ""
    /// SF Symbols: "textformat.abc"
    case abc = ""
    /// SF Symbols: "text.quote"
    case formatQuote = ""
    /// SF Symbols: "captions.bubble"
    case subtitles = ""
    /// SF Symbols: "flag.checkered"
    case flag = ""
    /// SF Symbols: "trophy.fill"
    case emojiEvents = ""
    /// SF Symbols: "play.circle.fill"
    case playCircle = ""
    /// SF Symbols: "pause.circle"
    case pauseCircle = ""
    /// SF Symbols: "square.stack.3d.up"
    case layers = ""
    /// SF Symbols: "square.stack.3d.up.slash"
    case layersClear = ""
    /// SF Symbols: "bubble.left.and.bubble.right"
    case translate = ""
    /// SF Symbols: "building.columns"
    case accountBalance = ""
    /// SF Symbols: "testtube.2"
    case science = ""
    /// SF Symbols: "paintpalette"
    case palette = ""
    /// SF Symbols: "paintbrush"
    case brush = ""
    /// SF Symbols: "figure.run"
    case directionsRun = ""
    /// SF Symbols: "sun.max"
    case lightMode = ""
    /// SF Symbols: "moon"
    case darkMode = ""
    /// SF Symbols: "circle.lefthalf.filled"
    case contrast = ""
    /// SF Symbols: "circle"
    case circle = ""
    /// SF Symbols: "circle.dashed"
    case radioButtonUnchecked = ""
    /// SF Symbols: "arrow.down.to.line"
    case arrowDownward = ""
    /// SF Symbols: "arrow.up.to.line"
    case arrowUpward = ""
    /// SF Symbols: "printer"
    case print = ""
    /// SF Symbols: "1.circle"
    case looksOne = ""
    /// SF Symbols: "2.circle"
    case looksTwo = ""
    /// SF Symbols: "3.circle"
    case looks_3 = ""
    /// SF Symbols: "textformat"
    case textFields = ""
    /// SF Symbols: "arrow.uturn.backward"
    case undo = ""
    /// SF Symbols: "bolt.circle"
    case bolt = ""
    /// SF Symbols: "hourglass"
    case hourglassEmpty = ""
    /// SF Symbols: "chart.line.uptrend.xyaxis"
    case showChart = ""
    /// SF Symbols: "globe"
    case globe = ""
    /// SF Symbols: "globe.americas"
    case `public` = ""
    /// SF Symbols: "target"
    case target = ""
}

extension AstraIcon {
    /// Resolves a legacy SF Symbol name to the closest Material icon.
    static func fromSystemName(_ name: String) -> AstraIcon? {
        switch name {
        case "square.grid.2x2": return .gridView
        case "mic.circle": return .mic
        case "text.document": return .description
        case "doc.text": return .description
        case "square.stack": return .style
        case "questionmark.circle": return .help
        case "book": return .menuBook
        case "brain": return .psychology
        case "graduationcap": return .school
        case "chart.bar": return .barChart
        case "heart.circle": return .favorite
        case "gearshape": return .settings
        case "mic": return .mic
        case "mic.fill": return .mic
        case "pause": return .pause
        case "pause.fill": return .pause
        case "play": return .playArrow
        case "play.fill": return .playArrow
        case "stop.fill": return .stop
        case "waveform": return .graphicEq
        case "waveform.badge.mic": return .mic
        case "arrow.down.doc": return .download
        case "folder": return .folder
        case "timer": return .timer
        case "forward": return .arrowForward
        case "arrow.right": return .arrowForward
        case "arrow.left": return .arrowBack
        case "arrow.triangle.right": return .playArrow
        case "arrow.triangle.2.circlepath": return .refresh
        case "checkmark": return .check
        case "checkmark.circle": return .checkCircle
        case "checkmark.circle.fill": return .checkCircle
        case "checkmark.seal": return .verified
        case "checkmark.seal.fill": return .verified
        case "xmark.circle.fill": return .cancel
        case "exclamationmark.triangle.fill": return .warning
        case "exclamationmark.triangle": return .warning
        case "plus": return .add
        case "plus.circle": return .addCircle
        case "plus.circle.fill": return .addCircle
        case "magnifyingglass": return .search
        case "sparkles": return .autoAwesome
        case "trash": return .delete
        case "paperplane": return .send
        case "square.and.arrow.up": return .share
        case "doc.on.doc": return .contentCopy
        case "doc.richtext": return .article
        case "doc.fill": return .description
        case "star": return .star
        case "star.fill": return .star
        case "clock": return .schedule
        case "clock.arrow.2.circlepath": return .history
        case "calendar": return .calendarMonth
        case "link.circle": return .link
        case "info.circle": return .info
        case "pencil": return .edit
        case "pencil.circle": return .edit
        case "pencil.and.outline": return .editNote
        case "chevron.down": return .expandMore
        case "chevron.right": return .chevronRight
        case "checklist": return .checklist
        case "list.clipboard": return .checklist
        case "list.bullet.rectangle": return .notes
        case "list.bullet.indent": return .list
        case "lightbulb": return .lightbulb
        case "lightbulb.fill": return .lightbulb
        case "eye": return .visibility
        case "person": return .person
        case "person.2": return .group
        case "gauge": return .speed
        case "function": return .functions
        case "textformat.abc": return .abc
        case "text.quote": return .formatQuote
        case "captions.bubble": return .subtitles
        case "flag.checkered": return .flag
        case "trophy.fill": return .emojiEvents
        case "play.circle.fill": return .playCircle
        case "pause.circle": return .pauseCircle
        case "square.stack.3d.up": return .layers
        case "square.stack.3d.up.slash": return .layersClear
        case "book.closed": return .menuBook
        case "bubble.left.and.bubble.right": return .translate
        case "building.columns": return .accountBalance
        case "testtube.2": return .science
        case "paintpalette": return .palette
        case "paintbrush": return .brush
        case "figure.run": return .directionsRun
        case "heart": return .favorite
        case "sun.max": return .lightMode
        case "moon": return .darkMode
        case "circle.lefthalf.filled": return .contrast
        case "circle": return .circle
        case "circle.dashed": return .radioButtonUnchecked
        case "arrow.down.to.line": return .arrowDownward
        case "arrow.up.to.line": return .arrowUpward
        case "printer": return .print
        case "text.book.closed": return .menuBook
        case "1.circle": return .looksOne
        case "2.circle": return .looksTwo
        case "3.circle": return .looks_3
        case "textformat": return .textFields
        case "xmark.circle": return .cancel
        case "arrow.uturn.backward": return .undo
        case "bolt.circle": return .bolt
        case "hourglass": return .hourglassEmpty
        case "chart.line.uptrend.xyaxis": return .showChart
        case "globe": return .globe
        case "globe.americas": return .`public`
        case "target": return .target
        case "text.alignleft": return .notes
        default: return nil
        }
    }
}