// scripts/swap_icons_dynamic.js
// Second migration pass: dynamic icon usages (ternaries, .icon properties,
// helper params of type String) -> AstraIcon / AstraIconView.
//
// Usage: node scripts/swap_icons_dynamic.js

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const src = path.join(root, 'AstraNotes');

const edits = [
  // ============ Ternary replacements ============
  // [file, old, new]
  ['Views/IB/EETrackerView.swift',
   'Image(systemName: isComplete ? "checkmark.circle.fill" : "circle")',
   'AstraIconView(isComplete ? .checkCircle : .circle, size: 14)'],
  ['Views/IB/EETrackerView.swift',
   'Image(systemName: isExpanded ? "chevron.down" : "chevron.right")',
   'AstraIconView(isExpanded ? .expandMore : .chevronRight, size: 11)'],
  ['Views/IB/EETrackerView.swift',
   'Image(systemName: tab.icon)',
   'AstraIconView(tab.astraIcon, size: 12)'],
  ['Views/IB/EETrackerView.swift',
   'Image(systemName: icon)',
   'AstraIconView(icon, size: 14)'],
  ['Views/IB/EETrackerView.swift',
   'Image(systemName: "arrow.triangle.right")',
   'AstraIconView(.playArrow, size: 9)'],
  ['Views/IB/CASJournalView.swift',
   'Image(systemName: entry.supervisorApproved ? "checkmark.seal.fill" : "checkmark.seal")',
   'AstraIconView(.verified, size: 14)'],
  ['Views/IB/CASJournalView.swift',
   'Image(systemName: isAchieved ? "checkmark" : "circle")',
   'AstraIconView(isAchieved ? .check : .circle, size: 13)'],
  ['Views/IB/CASJournalView.swift',
   'Image(systemName: entry.casCategory.icon)',
   'AstraIconView(entry.casCategory.astraIcon, size: 18)'],
  ['Views/IB/CASJournalView.swift',
   'Image(systemName: category.icon)',
   'AstraIconView(category.astraIcon, size: 13)'],
  ['Views/IB/CASJournalView.swift',
   'Image(systemName: icon)',
   'AstraIconView(icon, size: 11)'],
  ['Views/IB/CASJournalView.swift',
   'Image(systemName: "plus.circle.fill")',
   'AstraIconView(.addCircle, size: 14)'],
  ['Views/IB/IAWorkbenchView.swift',
   'Image(systemName: section.isComplete ? "checkmark.seal.fill" : "circle.dashed")',
   'AstraIconView(section.isComplete ? .verified : .radioButtonUnchecked, size: 16)'],
  ['Views/IB/IAWorkbenchView.swift',
   'Image(systemName: icon)',
   'AstraIconView(icon, size: 18)'],
  ['Views/Settings/SettingsView.swift',
   'Image(systemName: mode.icon)',
   'AstraIconView(mode.astraIcon, size: 12)'],
  ['Views/Recording/RecordingView.swift',
   'Image(systemName: buttonIcon)',
   'AstraIconView(buttonIcon, size: 18)'],
  ['Views/Recording/RecordingView.swift',
   'Image(systemName: "checkmark.circle.fill")',
   'AstraIconView(.checkCircle, size: 12)'],
  ['Views/Study/StudyGuideView.swift',
   'Image(systemName: note.type.icon)',
   'AstraIconView(note.type.astraIcon, size: 16)'],
  ['Views/Study/StudyGuideView.swift',
   'Image(systemName: isExpanded ? "chevron.down" : "chevron.right")',
   'AstraIconView(isExpanded ? .expandMore : .chevronRight, size: 12)'],
  ['Views/Study/StudyGuideView.swift',
   'Image(systemName: "book.closed")',
   'AstraIconView(.menuBook, size: 14)'],
  ['Views/Study/StudyGuideView.swift',
   'Image(systemName: "checkmark.circle.fill")',
   'AstraIconView(.checkCircle, size: 14)'],
  ['Views/Study/StudyGuideView.swift',
   'Image(systemName: "star.fill")',
   'AstraIconView(.star, size: 12)'],
  ['Views/Sidebar/SidebarView.swift',
   'Image(systemName: icon)',
   'AstraIconView(icon, size: 13)'],
  ['Views/Notes/NoteDetailView.swift',
   'Image(systemName: note.type.icon)',
   'AstraIconView(note.type.astraIcon, size: 12)'],
  ['Views/IB/TOKPlannerView.swift',
   'Image(systemName: icon)',
   'AstraIconView(icon, size: 12)'],
  ['Views/Study/FlashcardReviewView.swift',
   'Image(systemName: isStudyMode ? "eye" : "clock")',
   'AstraIconView(isStudyMode ? .visibility : .schedule, size: 12)'],
  ['Views/Study/FlashcardReviewView.swift',
   'Image(systemName: icon)',
   'AstraIconView(icon, size: 20)'],
  ['Views/Study/FlashcardReviewView.swift',
   'Image(systemName: "checkmark.seal.fill")',
   'AstraIconView(.verified, size: 36)'],
  ['Views/Study/FlashcardReviewView.swift',
   'Image(systemName: "forward")',
   'AstraIconView(.arrowForward, size: 20)'],
  ['Views/Study/QuizView.swift',
   'Image(systemName: hasEnough ? "checkmark.circle.fill" : "exclamationmark.triangle.fill")',
   'AstraIconView(hasEnough ? .checkCircle : .warning, size: 14)'],
  ['Views/Study/QuizView.swift',
   'Image(systemName: timeRemaining <= 10 ? "timer" : "clock")',
   'AstraIconView(timeRemaining <= 10 ? .timer : .schedule, size: 14)'],
  ['Views/Study/QuizView.swift',
   'Image(systemName: currentIndex + 1 < quizQuestions.count ? "arrow.right" : "flag.checkered")',
   'AstraIconView(currentIndex + 1 < quizQuestions.count ? .arrowForward : .flag, size: 14)'],
  ['Views/Study/QuizView.swift',
   'Image(systemName: isCorrect ? "checkmark.circle.fill" : "xmark.circle.fill")',
   'AstraIconView(isCorrect ? .checkCircle : .cancel, size: 16)'],
  ['Views/Study/QuizView.swift',
   'Image(systemName: answer.isCorrect ? "checkmark.circle.fill" : "xmark.circle.fill")',
   'AstraIconView(answer.isCorrect ? .checkCircle : .cancel, size: 14)'],
  ['Views/Study/QuizView.swift',
   'Image(systemName: score == quizQuestions.count ? "trophy.fill" : "chart.bar")',
   'AstraIconView(score == quizQuestions.count ? .emojiEvents : .barChart, size: 16)'],
  ['Views/Study/QuizView.swift',
   'Image(systemName: "list.clipboard")',
   'AstraIconView(.checklist, size: 14)'],
  ['Views/Study/QuizView.swift',
   'Image(systemName: icon)',
   'AstraIconView(icon, size: 16)'],
  ['Views/Study/QuizView.swift',
   'Image(systemName: "lightbulb.fill")',
   'AstraIconView(.lightbulb, size: 14)'],
  ['Views/Transcription/TranscriptionView.swift',
   'Image(systemName: icon)',
   'AstraIconView(icon, size: 12)'],

  // ============ Helper signatures: icon: String -> icon: AstraIcon ============
  ['Views/Dashboard/DashboardView.swift',
   'private func miniStat(icon: String, value: String, label: String) -> some View {',
   'private func miniStat(icon: AstraIcon, value: String, label: String) -> some View {'],
  ['Views/IB/CASJournalView.swift',
   '        icon: String,',
   '        icon: AstraIcon,'],
  ['Views/IB/EETrackerView.swift',
   'private func rppfCard(_ text: String?, title: String, icon: String, color: Color) -> some View {',
   'private func rppfCard(_ text: String?, title: String, icon: AstraIcon, color: Color) -> some View {'],
  ['Views/IB/EETrackerView.swift',
   'private func sectionLabel(_ title: String, icon: String) -> some View {',
   'private func sectionLabel(_ title: String, icon: AstraIcon) -> some View {'],
  ['Views/IB/IAWorkbenchView.swift',
   'private func overviewStatCard(title: String, value: String, icon: String, color: Color) -> some View {',
   'private func overviewStatCard(title: String, value: String, icon: AstraIcon, color: Color) -> some View {'],
  ['Views/IB/IAWorkbenchView.swift',
   '        icon: String,',
   '        icon: AstraIcon,'],
  ['Views/IB/IAWorkbenchView.swift',
   'private func sectionLabel(_ title: String, icon: String) -> some View {',
   'private func sectionLabel(_ title: String, icon: AstraIcon) -> some View {'],
  ['Views/Transcription/TranscriptionView.swift',
   'private func statBadge(icon: String, value: String, label: String) -> some View {',
   'private func statBadge(icon: AstraIcon, value: String, label: String) -> some View {'],
  ['Views/Study/FlashcardReviewView.swift',
   '        icon: String,',
   '        icon: AstraIcon,'],
  ['Views/Sidebar/SidebarView.swift',
   '        icon: String,',
   '        icon: AstraIcon,'],
  ['Views/Study/QuizView.swift',
   'private func statCard(icon: String, label: String, value: String, color: Color) -> some View {',
   'private func statCard(icon: AstraIcon, label: String, value: String, color: Color) -> some View {'],
  ['Views/IB/TOKPlannerView.swift',
   'private func sectionLabel(_ title: String, icon: String) -> some View {',
   'private func sectionLabel(_ title: String, icon: AstraIcon) -> some View {'],
];

let total = 0;
for (const [file, old, nw] of edits) {
  const p = path.join(src, file);
  let text = fs.readFileSync(p, 'utf8');
  const n = text.split(old).length - 1;
  if (n === 0) {
    console.log('  SKIP (not found): ' + file + ' :: ' + old.slice(0, 60));
    continue;
  }
  text = text.split(old).join(nw);
  fs.writeFileSync(p, text);
  total += n;
  console.log('  ' + file + ': ' + n + 'x ' + old.slice(0, 50) + '...');
}
console.log('Total dynamic replacements: ' + total);
